;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        c-electric-delete-forward
        end-of-visual-line
        sp--self-insert-command
        sp-forward-slurp-sexp
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        dired-unmark-backward
        ))
